databases:
  - name: bluehawks-db
    databaseName: bluehawks
    user: bluehawks

services:
  - type: web
    name: bluehawks
    env: python
    plan: free
    buildCommand: cd backend && chmod +x build.sh && ./build.sh
    startCommand: cd backend && gunicorn bluehawks.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: DATABASE_URL
        fromDatabase:
          name: bluehawks-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DEBUG
        value: false
      - key: DJANGO_SETTINGS_MODULE
        value: bluehawks.settings_production 