# Generated by Django 5.2.4 on 2025-08-09 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainwebsite', '0003_service'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactsubmission',
            options={'ordering': ['-submitted_at'], 'verbose_name': 'Contact Submission', 'verbose_name_plural': 'Contact Submissions'},
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, help_text='IP address of submitter', null=True),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='is_processed',
            field=models.BooleanField(default=False, help_text='Has this submission been processed?'),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='notes',
            field=models.TextField(blank=True, help_text='Admin notes about this submission', null=True),
        ),
        migrations.AddField(
            model_name='contactsubmission',
            name='user_agent',
            field=models.TextField(blank=True, help_text='Browser user agent', null=True),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='city',
            field=models.CharField(blank=True, help_text='City name (optional, letters and spaces only)', max_length=50, null=True, validators=[django.core.validators.RegexValidator(code='invalid_city', message='City name can only contain letters and spaces.', regex='^[a-zA-Z\\s]+$'), django.core.validators.MinLengthValidator(2, message='City name must be at least 2 characters long.')]),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='email',
            field=models.EmailField(help_text='Valid email address (max 100 characters)', max_length=100),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='message',
            field=models.TextField(help_text='Your message (10-1000 characters)', validators=[django.core.validators.MinLengthValidator(10, message='Message must be at least 10 characters long.'), django.core.validators.MaxLengthValidator(1000, message='Message cannot exceed 1000 characters.')]),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='name',
            field=models.CharField(help_text='Full name (2-50 characters, letters and spaces only)', max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_name', message='Name can only contain letters and spaces.', regex='^[a-zA-Z\\s]+$'), django.core.validators.MinLengthValidator(2, message='Name must be at least 2 characters long.'), django.core.validators.MaxLengthValidator(50, message='Name cannot exceed 50 characters.')]),
        ),
        migrations.AlterField(
            model_name='contactsubmission',
            name='phone',
            field=models.CharField(blank=True, help_text='Pakistan phone number (optional)', max_length=20, null=True, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='Please enter a valid Pakistan phone number.', regex='^(\\+92|92|0)?[0-9\\s\\-\\(\\)]{10,20}$')]),
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['-submitted_at'], name='mainwebsite_submitt_ebeef8_idx'),
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['email'], name='mainwebsite_email_a7385c_idx'),
        ),
        migrations.AddIndex(
            model_name='contactsubmission',
            index=models.Index(fields=['is_processed'], name='mainwebsite_is_proc_c03970_idx'),
        ),
    ]
